name: "Mihomo Global VPN"
description: "Mihomo (Clash Meta) with TUN mode for host and network-wide VPN."
version: "1.0.5"
slug: "mihomo-addon"
startup: services
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
init: false
host_network: true
map:
  - homeassistant_config:rw
privileged:
  - NET_ADMIN
  - NET_RAW
  - SYS_ADMIN
  - SYS_MODULE
full_access: true
options:
  config_path: "/config/mihomo/config.yaml"
  config_content: ""
schema:
  config_path: str
  config_content: str
